name: metaverse-app
services:
  http:
    build: .
    container_name: metaverse-http
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: metaverse_postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - metaverse_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  metaverse_data:


